version: '3.8'

services:
  # 1. PostgreSQL - Lưu trữ thông tin User, Friends, Rooms
  postgres-db:
    image: postgres:15-alpine
    container_name: social_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: SecretPassword123!
      POSTGRES_DB: SocialNetworkDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. MongoDB - Lưu trữ lịch sử tin nhắn Chat
  mongo-db:
    image: mongo:7.0
    container_name: social_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: SecretPassword123!
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Redis - Làm Message Broker (Pub/Sub) và Cache
  redis-db:
    image: redis:7-alpine
    container_name: social_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass "SecretPassword123!"
    volumes:
      - redis_data:/data

# Khai báo Volumes để dữ liệu không bị mất khi xóa Container
volumes:
  postgres_data:
  mongo_data:
  redis_data: