/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * SocialNetwork.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import { customMutator } from './mutator';
export interface AdminCommentDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  postId?: number | string;
  authorUsername?: string;
  /** @nullable */
  authorAvatarUrl?: string | null;
  content?: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  parentId?: number | string | null;
  /** @nullable */
  postContentPreview?: string | null;
  createdAt?: string;
}

export interface AdminPostDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  authorUsername?: string;
  /** @nullable */
  authorAvatarUrl?: string | null;
  content?: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  likesCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  commentsCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  reportCount?: number | string;
  createdAt?: string;
}

export interface AdminResetPasswordDto {
  /**
     * @minLength 6
     * @maxLength 100
     */
  newPassword: string;
}

export interface AdminStatsDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalUsers?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalPosts?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalComments?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalMessages?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalFollows?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pendingReports?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  newUsersToday?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  newPostsToday?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  newCommentsToday?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  activeUsersWeek?: number | string;
}

export interface AdminUserDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  username?: string;
  /** @nullable */
  fullName?: string | null;
  email?: string;
  role?: string;
  isActive?: boolean;
  /** @nullable */
  avatarUrl?: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  postCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  followerCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  followingCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  commentCount?: number | string;
  createdAt?: string;
}

export interface ApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: unknown;
}

export interface ApiResponseOfAdminStatsDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | AdminStatsDto;
}

export interface UserBadgeDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  badgeId?: number | string;
  name?: string;
  /** @nullable */
  description?: string | null;
  icon?: string;
  color?: string;
  earnedAt?: string;
  isDisplayed?: boolean;
}

export interface UserDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  username?: string;
  email?: string;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  hometown?: string | null;
  /** @nullable */
  gender?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  coverUrl?: string | null;
  /** @nullable */
  bio?: string | null;
  role?: string;
  createdAt?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  followersCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  followingCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  postsCount?: number | string;
  isFollowing?: boolean;
  displayedBadge?: null | UserBadgeDto;
}

export interface AuthResponseDto {
  token?: string;
  user?: UserDto;
}

export interface ApiResponseOfAuthResponseDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | AuthResponseDto;
}

export interface BadgeDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  name?: string;
  /** @nullable */
  description?: string | null;
  icon?: string;
  color?: string;
  conditionType?: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  conditionValue?: number | string | null;
  isManualOnly?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  usersCount?: number | string;
}

export interface ApiResponseOfBadgeDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | BadgeDto;
}

export interface UserSummaryDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  username?: string;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  followersCount?: number | null;
  displayedBadge?: null | UserBadgeDto;
}

export interface CommentDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  postId?: number | string;
  user?: UserSummaryDto;
  content?: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  parentId?: number | string | null;
  createdAt?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  repliesCount?: number | string;
}

export interface ApiResponseOfCommentDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | CommentDto;
}

export interface MessageDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  conversationId?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  senderId?: number | string;
  content?: string;
  isRead?: boolean;
  createdAt?: string;
}

export interface ConversationDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  createdAt?: string;
  participants?: UserSummaryDto[];
  lastMessage?: null | MessageDto;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  unreadCount?: number | string;
}

export interface ApiResponseOfConversationDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | ConversationDto;
}

export interface FollowResultDto {
  isFollowing?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  followersCount?: number | string;
}

export interface ApiResponseOfFollowResultDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | FollowResultDto;
}

export interface DailyCountDto {
  date?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  count?: number | string;
}

export interface GrowthChartDto {
  users?: DailyCountDto[];
  posts?: DailyCountDto[];
  comments?: DailyCountDto[];
}

export interface ApiResponseOfGrowthChartDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | GrowthChartDto;
}

export type LikeResultDtoReactionCounts = {[key: string]: number | string};

export interface LikeResultDto {
  isLiked?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  likesCount?: number | string;
  /** @nullable */
  reactionType?: string | null;
  reactionCounts?: LikeResultDtoReactionCounts;
}

export interface ApiResponseOfLikeResultDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | LikeResultDto;
}

export interface ApiResponseOfListOfBadgeDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: BadgeDto[] | null;
}

export interface BadgeProgressDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  badgeId?: number | string;
  name?: string;
  /** @nullable */
  description?: string | null;
  icon?: string;
  color?: string;
  conditionType?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  conditionValue?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  currentValue?: number | string;
  isEarned?: boolean;
  /** @nullable */
  earnedAt?: string | null;
}

export interface ApiResponseOfListOfBadgeProgressDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: BadgeProgressDto[] | null;
}

export interface ApiResponseOfListOfCommentDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: CommentDto[] | null;
}

export interface TrendingHashtagDto {
  tag?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  postCount?: number | string;
}

export interface ApiResponseOfListOfTrendingHashtagDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: TrendingHashtagDto[] | null;
}

export interface ApiResponseOfListOfUserBadgeDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: UserBadgeDto[] | null;
}

export interface ApiResponseOfListOfUserSummaryDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: UserSummaryDto[] | null;
}

export interface ApiResponseOfMessageDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | MessageDto;
}

export interface PagedResultOfAdminCommentDto {
  items?: AdminCommentDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
  hasNextPage?: boolean;
}

export interface ApiResponseOfPagedResultOfAdminCommentDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | PagedResultOfAdminCommentDto;
}

export interface PagedResultOfAdminPostDto {
  items?: AdminPostDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
  hasNextPage?: boolean;
}

export interface ApiResponseOfPagedResultOfAdminPostDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | PagedResultOfAdminPostDto;
}

export interface PagedResultOfAdminUserDto {
  items?: AdminUserDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
  hasNextPage?: boolean;
}

export interface ApiResponseOfPagedResultOfAdminUserDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | PagedResultOfAdminUserDto;
}

export interface PagedResultOfCommentDto {
  items?: CommentDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
  hasNextPage?: boolean;
}

export interface ApiResponseOfPagedResultOfCommentDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | PagedResultOfCommentDto;
}

export interface PagedResultOfConversationDto {
  items?: ConversationDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
  hasNextPage?: boolean;
}

export interface ApiResponseOfPagedResultOfConversationDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | PagedResultOfConversationDto;
}

export interface PagedResultOfMessageDto {
  items?: MessageDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
  hasNextPage?: boolean;
}

export interface ApiResponseOfPagedResultOfMessageDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | PagedResultOfMessageDto;
}

export interface NotificationDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  actor?: UserSummaryDto;
  notificationType?: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  entityId?: number | string | null;
  isRead?: boolean;
  createdAt?: string;
}

export interface PagedResultOfNotificationDto {
  items?: NotificationDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
  hasNextPage?: boolean;
}

export interface ApiResponseOfPagedResultOfNotificationDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | PagedResultOfNotificationDto;
}

export type PostDtoReactionCounts = {[key: string]: number | string};

export interface PostDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  user?: UserSummaryDto;
  content?: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  videoUrl?: string | null;
  createdAt?: string;
  updatedAt?: string;
  visibility?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  likesCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  commentsCount?: number | string;
  isLiked?: boolean;
  /** @nullable */
  myReaction?: string | null;
  reactionCounts?: PostDtoReactionCounts;
  hashtags?: string[];
}

export interface PagedResultOfPostDto {
  items?: PostDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
  hasNextPage?: boolean;
}

export interface ApiResponseOfPagedResultOfPostDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | PagedResultOfPostDto;
}

export interface ReportDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  reporterUsername?: string;
  /** @nullable */
  targetUsername?: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  targetPostId?: number | string | null;
  /** @nullable */
  targetPostContent?: string | null;
  reason?: string;
  /** @nullable */
  detail?: string | null;
  status?: string;
  createdAt?: string;
  /** @nullable */
  resolvedAt?: string | null;
}

export interface PagedResultOfReportDto {
  items?: ReportDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
  hasNextPage?: boolean;
}

export interface ApiResponseOfPagedResultOfReportDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | PagedResultOfReportDto;
}

export interface PagedResultOfUserSummaryDto {
  items?: UserSummaryDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
  hasNextPage?: boolean;
}

export interface ApiResponseOfPagedResultOfUserSummaryDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | PagedResultOfUserSummaryDto;
}

export interface ApiResponseOfPostDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | PostDto;
}

export interface UnreadCountDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  count?: number | string;
}

export interface ApiResponseOfUnreadCountDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | UnreadCountDto;
}

export interface UnreadNotificationCountDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  count?: number | string;
}

export interface ApiResponseOfUnreadNotificationCountDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | UnreadNotificationCountDto;
}

export interface UploadResultDto {
  url?: string;
}

export interface ApiResponseOfUploadResultDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | UploadResultDto;
}

export interface ApiResponseOfUserDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: null | UserDto;
}

export interface ChangePasswordDto {
  currentPassword: string;
  /** @minLength 6 */
  newPassword: string;
}

export interface ChangeRoleDto {
  /**
     * @minLength 0
     * @maxLength 50
     */
  role: string;
}

export interface CreateBadgeDto {
  /**
     * @minLength 0
     * @maxLength 100
     */
  name: string;
  /**
     * @minLength 0
     * @maxLength 500
     * @nullable
     */
  description?: string | null;
  /**
     * @minLength 0
     * @maxLength 200
     */
  icon?: string;
  /**
     * @minLength 0
     * @maxLength 10
     */
  color?: string;
  /**
     * @minLength 0
     * @maxLength 30
     */
  conditionType: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  conditionValue?: number | string | null;
  isManualOnly?: boolean;
}

export interface CreateCommentDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  postId?: number | string;
  content?: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  parentId?: number | string | null;
}

export interface CreateMessageDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  conversationId?: number | string;
  /**
     * @minLength 1
     * @maxLength 2000
     */
  content: string;
}

export interface CreatePostDto {
  /**
     * @minLength 1
     * @maxLength 2000
     */
  content: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  videoUrl?: string | null;
  visibility?: string;
}

export interface CreateReportDto {
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  targetUserId?: number | string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  targetPostId?: number | string | null;
  /**
     * @minLength 0
     * @maxLength 50
     */
  reason: string;
  /**
     * @minLength 0
     * @maxLength 500
     * @nullable
     */
  detail?: string | null;
}

export interface LoginDto {
  emailOrUsername: string;
  password: string;
}

export interface ReactDto {
  reactionType?: string;
}

export interface RegisterDto {
  /**
     * @minLength 0
     * @maxLength 50
     */
  username: string;
  /**
     * @minLength 0
     * @maxLength 100
     */
  email: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  password: string;
  /**
     * @minLength 0
     * @maxLength 100
     * @nullable
     */
  fullName?: string | null;
  /** @nullable */
  dateOfBirth?: string | null;
}

export interface SetDisplayBadgeDto {
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  badgeId?: number | string | null;
}

export interface StartConversationDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  targetUserId: number | string;
}

export interface UpdateBadgeDto {
  /**
     * @minLength 0
     * @maxLength 100
     * @nullable
     */
  name?: string | null;
  /**
     * @minLength 0
     * @maxLength 500
     * @nullable
     */
  description?: string | null;
  /**
     * @minLength 0
     * @maxLength 200
     * @nullable
     */
  icon?: string | null;
  /**
     * @minLength 0
     * @maxLength 10
     * @nullable
     */
  color?: string | null;
  /**
     * @minLength 0
     * @maxLength 30
     * @nullable
     */
  conditionType?: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  conditionValue?: number | string | null;
  /** @nullable */
  isManualOnly?: boolean | null;
}

export interface UpdatePostDto {
  /**
     * @minLength 1
     * @maxLength 2000
     */
  content: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  visibility?: string | null;
}

export interface UpdateUserDto {
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  coverUrl?: string | null;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  hometown?: string | null;
  /** @nullable */
  gender?: string | null;
}

export type GetApiAdminGrowthChartParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
days?: number | string;
};

export type GetApiAdminUsersParams = {
q?: string;
role?: string;
status?: string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type PutApiAdminUsersIdBanParams = {
ban?: boolean;
};

export type GetApiAdminPostsParams = {
q?: string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiAdminCommentsParams = {
q?: string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
postId?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiAdminReportsParams = {
status?: string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiCommentsPostPostIdParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiConversationsParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiConversationsIdMessagesParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiNotificationsParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiPostsFeedParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiPostsUserUserIdParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiPostsHashtagTagParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiPostsTrendingHashtagsParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
limit?: number | string;
};

export type GetApiPostsSearchParams = {
q?: string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type PostApiUploadImageBodyHeaders = {[key: string]: string[]};

export type PostApiUploadImageBody = {
  ContentType?: string;
  ContentDisposition?: string;
  Headers?: PostApiUploadImageBodyHeaders;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  Length?: number | string;
  Name?: string;
  FileName?: string;
};

export type GetApiUsersIdFollowersParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiUsersIdFollowingParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};

export type GetApiUsersSearchParams = {
q?: string;
};

export const getSocialNetworkApiV1 = () => {
const getApiAdminStats = (

 ) => {
      return customMutator<ApiResponseOfAdminStatsDto>(
      {url: `/api/Admin/stats`, method: 'GET'
    },
      );
    }

const getApiAdminGrowthChart = (
    params?: GetApiAdminGrowthChartParams,
 ) => {
      return customMutator<ApiResponseOfGrowthChartDto>(
      {url: `/api/Admin/growth-chart`, method: 'GET',
        params
    },
      );
    }

const getApiAdminUsers = (
    params?: GetApiAdminUsersParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfAdminUserDto>(
      {url: `/api/Admin/users`, method: 'GET',
        params
    },
      );
    }

const putApiAdminUsersIdBan = (
    id: number | string,
    params?: PutApiAdminUsersIdBanParams,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Admin/users/${id}/ban`, method: 'PUT',
        params
    },
      );
    }

const putApiAdminUsersIdRole = (
    id: number | string,
    changeRoleDto: ChangeRoleDto,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Admin/users/${id}/role`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: changeRoleDto
    },
      );
    }

const putApiAdminUsersIdResetPassword = (
    id: number | string,
    adminResetPasswordDto: AdminResetPasswordDto,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Admin/users/${id}/reset-password`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: adminResetPasswordDto
    },
      );
    }

const deleteApiAdminUsersId = (
    id: number | string,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Admin/users/${id}`, method: 'DELETE'
    },
      );
    }

const getApiAdminPosts = (
    params?: GetApiAdminPostsParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfAdminPostDto>(
      {url: `/api/Admin/posts`, method: 'GET',
        params
    },
      );
    }

const deleteApiAdminPostsId = (
    id: number | string,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Admin/posts/${id}`, method: 'DELETE'
    },
      );
    }

const getApiAdminComments = (
    params?: GetApiAdminCommentsParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfAdminCommentDto>(
      {url: `/api/Admin/comments`, method: 'GET',
        params
    },
      );
    }

const deleteApiAdminCommentsId = (
    id: number | string,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Admin/comments/${id}`, method: 'DELETE'
    },
      );
    }

const getApiAdminReports = (
    params?: GetApiAdminReportsParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfReportDto>(
      {url: `/api/Admin/reports`, method: 'GET',
        params
    },
      );
    }

const putApiAdminReportsIdResolve = (
    id: number | string,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Admin/reports/${id}/resolve`, method: 'PUT'
    },
      );
    }

const deleteApiAdminReportsId = (
    id: number | string,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Admin/reports/${id}`, method: 'DELETE'
    },
      );
    }

const getApiAdminBadges = (

 ) => {
      return customMutator<ApiResponseOfListOfBadgeDto>(
      {url: `/api/Admin/badges`, method: 'GET'
    },
      );
    }

const postApiAdminBadges = (
    createBadgeDto: CreateBadgeDto,
 ) => {
      return customMutator<ApiResponseOfBadgeDto>(
      {url: `/api/Admin/badges`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBadgeDto
    },
      );
    }

const putApiAdminBadgesId = (
    id: number | string,
    updateBadgeDto: UpdateBadgeDto,
 ) => {
      return customMutator<ApiResponseOfBadgeDto>(
      {url: `/api/Admin/badges/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateBadgeDto
    },
      );
    }

const deleteApiAdminBadgesId = (
    id: number | string,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Admin/badges/${id}`, method: 'DELETE'
    },
      );
    }

const postApiAdminUsersUserIdBadgesBadgeId = (
    userId: number | string,
    badgeId: number | string,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Admin/users/${userId}/badges/${badgeId}`, method: 'POST'
    },
      );
    }

const deleteApiAdminUsersUserIdBadgesBadgeId = (
    userId: number | string,
    badgeId: number | string,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Admin/users/${userId}/badges/${badgeId}`, method: 'DELETE'
    },
      );
    }

const postApiAuthRegister = (
    registerDto: RegisterDto,
 ) => {
      return customMutator<ApiResponseOfAuthResponseDto>(
      {url: `/api/Auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerDto
    },
      );
    }

const postApiAuthLogin = (
    loginDto: LoginDto,
 ) => {
      return customMutator<ApiResponseOfAuthResponseDto>(
      {url: `/api/Auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto
    },
      );
    }

const getApiAuthMe = (

 ) => {
      return customMutator<ApiResponseOfUserDto>(
      {url: `/api/Auth/me`, method: 'GET'
    },
      );
    }

const getApiBadges = (

 ) => {
      return customMutator<ApiResponseOfListOfBadgeDto>(
      {url: `/api/Badges`, method: 'GET'
    },
      );
    }

const getApiBadgesUserUserId = (
    userId: number | string,
 ) => {
      return customMutator<ApiResponseOfListOfUserBadgeDto>(
      {url: `/api/Badges/user/${userId}`, method: 'GET'
    },
      );
    }

const getApiBadgesProgress = (

 ) => {
      return customMutator<ApiResponseOfListOfBadgeProgressDto>(
      {url: `/api/Badges/progress`, method: 'GET'
    },
      );
    }

const putApiBadgesDisplay = (
    setDisplayBadgeDto: SetDisplayBadgeDto,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Badges/display`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setDisplayBadgeDto
    },
      );
    }

const getApiCommentsPostPostId = (
    postId: number,
    params?: GetApiCommentsPostPostIdParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfCommentDto>(
      {url: `/api/Comments/post/${postId}`, method: 'GET',
        params
    },
      );
    }

const getApiCommentsCommentIdReplies = (
    commentId: number,
 ) => {
      return customMutator<ApiResponseOfListOfCommentDto>(
      {url: `/api/Comments/${commentId}/replies`, method: 'GET'
    },
      );
    }

const postApiComments = (
    createCommentDto: CreateCommentDto,
 ) => {
      return customMutator<ApiResponseOfCommentDto>(
      {url: `/api/Comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCommentDto
    },
      );
    }

const deleteApiCommentsId = (
    id: number,
 ) => {
      return customMutator<void>(
      {url: `/api/Comments/${id}`, method: 'DELETE'
    },
      );
    }

const getApiConversations = (
    params?: GetApiConversationsParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfConversationDto>(
      {url: `/api/Conversations`, method: 'GET',
        params
    },
      );
    }

const postApiConversations = (
    startConversationDto: StartConversationDto,
 ) => {
      return customMutator<ApiResponseOfConversationDto>(
      {url: `/api/Conversations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: startConversationDto
    },
      );
    }

const getApiConversationsIdMessages = (
    id: number,
    params?: GetApiConversationsIdMessagesParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfMessageDto>(
      {url: `/api/Conversations/${id}/messages`, method: 'GET',
        params
    },
      );
    }

const postApiConversationsIdMessages = (
    id: number,
    createMessageDto: CreateMessageDto,
 ) => {
      return customMutator<ApiResponseOfMessageDto>(
      {url: `/api/Conversations/${id}/messages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMessageDto
    },
      );
    }

const putApiConversationsIdRead = (
    id: number,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Conversations/${id}/read`, method: 'PUT'
    },
      );
    }

const getApiConversationsUnreadCount = (

 ) => {
      return customMutator<ApiResponseOfUnreadCountDto>(
      {url: `/api/Conversations/unread-count`, method: 'GET'
    },
      );
    }

const getApiMetrics = (

 ) => {
      return customMutator<void>(
      {url: `/api/Metrics`, method: 'GET'
    },
      );
    }

const getApiMetricsServer = (

 ) => {
      return customMutator<void>(
      {url: `/api/Metrics/server`, method: 'GET'
    },
      );
    }

const getApiNotifications = (
    params?: GetApiNotificationsParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfNotificationDto>(
      {url: `/api/Notifications`, method: 'GET',
        params
    },
      );
    }

const putApiNotificationsIdRead = (
    id: number,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Notifications/${id}/read`, method: 'PUT'
    },
      );
    }

const putApiNotificationsReadAll = (

 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Notifications/read-all`, method: 'PUT'
    },
      );
    }

const getApiNotificationsUnreadCount = (

 ) => {
      return customMutator<ApiResponseOfUnreadNotificationCountDto>(
      {url: `/api/Notifications/unread-count`, method: 'GET'
    },
      );
    }

const getApiPostsFeed = (
    params?: GetApiPostsFeedParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfPostDto>(
      {url: `/api/Posts/feed`, method: 'GET',
        params
    },
      );
    }

const getApiPostsUserUserId = (
    userId: number,
    params?: GetApiPostsUserUserIdParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfPostDto>(
      {url: `/api/Posts/user/${userId}`, method: 'GET',
        params
    },
      );
    }

const getApiPostsId = (
    id: number,
 ) => {
      return customMutator<ApiResponseOfPostDto>(
      {url: `/api/Posts/${id}`, method: 'GET'
    },
      );
    }

const putApiPostsId = (
    id: number,
    updatePostDto: UpdatePostDto,
 ) => {
      return customMutator<ApiResponseOfPostDto>(
      {url: `/api/Posts/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePostDto
    },
      );
    }

const deleteApiPostsId = (
    id: number,
 ) => {
      return customMutator<void>(
      {url: `/api/Posts/${id}`, method: 'DELETE'
    },
      );
    }

const postApiPosts = (
    createPostDto: CreatePostDto,
 ) => {
      return customMutator<ApiResponseOfPostDto>(
      {url: `/api/Posts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPostDto
    },
      );
    }

const postApiPostsIdLike = (
    id: number,
    nullReactDto: null | ReactDto,
 ) => {
      return customMutator<ApiResponseOfLikeResultDto>(
      {url: `/api/Posts/${id}/like`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: nullReactDto
    },
      );
    }

const getApiPostsHashtagTag = (
    tag: string,
    params?: GetApiPostsHashtagTagParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfPostDto>(
      {url: `/api/Posts/hashtag/${tag}`, method: 'GET',
        params
    },
      );
    }

const getApiPostsTrendingHashtags = (
    params?: GetApiPostsTrendingHashtagsParams,
 ) => {
      return customMutator<ApiResponseOfListOfTrendingHashtagDto>(
      {url: `/api/Posts/trending-hashtags`, method: 'GET',
        params
    },
      );
    }

const getApiPostsSearch = (
    params?: GetApiPostsSearchParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfPostDto>(
      {url: `/api/Posts/search`, method: 'GET',
        params
    },
      );
    }

const postApiReports = (
    createReportDto: CreateReportDto,
 ) => {
      return customMutator<ApiResponse>(
      {url: `/api/Reports`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createReportDto
    },
      );
    }

const postApiUploadImage = (
    postApiUploadImageBody: PostApiUploadImageBody,
 ) => {const formUrlEncoded = new URLSearchParams();
if(postApiUploadImageBody.ContentType !== undefined) {
 formUrlEncoded.append(`ContentType`, postApiUploadImageBody.ContentType);
 }
if(postApiUploadImageBody.ContentDisposition !== undefined) {
 formUrlEncoded.append(`ContentDisposition`, postApiUploadImageBody.ContentDisposition);
 }
if(postApiUploadImageBody.Headers !== undefined) {
 formUrlEncoded.append(`Headers`, JSON.stringify(postApiUploadImageBody.Headers));
 }
if(postApiUploadImageBody.Length !== undefined) {
 formUrlEncoded.append(`Length`, postApiUploadImageBody.Length.toString())
 }
if(postApiUploadImageBody.Name !== undefined) {
 formUrlEncoded.append(`Name`, postApiUploadImageBody.Name);
 }
if(postApiUploadImageBody.FileName !== undefined) {
 formUrlEncoded.append(`FileName`, postApiUploadImageBody.FileName);
 }

      return customMutator<ApiResponseOfUploadResultDto>(
      {url: `/api/Upload/image`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded
    },
      );
    }

const getApiUsersUsername = (
    username: string,
 ) => {
      return customMutator<ApiResponseOfUserDto>(
      {url: `/api/Users/${username}`, method: 'GET'
    },
      );
    }

const putApiUsersMe = (
    updateUserDto: UpdateUserDto,
 ) => {
      return customMutator<ApiResponseOfUserDto>(
      {url: `/api/Users/me`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateUserDto
    },
      );
    }

const postApiUsersIdFollow = (
    id: number,
 ) => {
      return customMutator<ApiResponseOfFollowResultDto>(
      {url: `/api/Users/${id}/follow`, method: 'POST'
    },
      );
    }

const getApiUsersIdFollowers = (
    id: number,
    params?: GetApiUsersIdFollowersParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfUserSummaryDto>(
      {url: `/api/Users/${id}/followers`, method: 'GET',
        params
    },
      );
    }

const getApiUsersIdFollowing = (
    id: number,
    params?: GetApiUsersIdFollowingParams,
 ) => {
      return customMutator<ApiResponseOfPagedResultOfUserSummaryDto>(
      {url: `/api/Users/${id}/following`, method: 'GET',
        params
    },
      );
    }

const getApiUsersSearch = (
    params?: GetApiUsersSearchParams,
 ) => {
      return customMutator<ApiResponseOfListOfUserSummaryDto>(
      {url: `/api/Users/search`, method: 'GET',
        params
    },
      );
    }

const getApiUsersSuggestions = (

 ) => {
      return customMutator<ApiResponseOfListOfUserSummaryDto>(
      {url: `/api/Users/suggestions`, method: 'GET'
    },
      );
    }

const putApiUsersMePassword = (
    changePasswordDto: ChangePasswordDto,
 ) => {
      return customMutator<void>(
      {url: `/api/Users/me/password`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordDto
    },
      );
    }

return {getApiAdminStats,getApiAdminGrowthChart,getApiAdminUsers,putApiAdminUsersIdBan,putApiAdminUsersIdRole,putApiAdminUsersIdResetPassword,deleteApiAdminUsersId,getApiAdminPosts,deleteApiAdminPostsId,getApiAdminComments,deleteApiAdminCommentsId,getApiAdminReports,putApiAdminReportsIdResolve,deleteApiAdminReportsId,getApiAdminBadges,postApiAdminBadges,putApiAdminBadgesId,deleteApiAdminBadgesId,postApiAdminUsersUserIdBadgesBadgeId,deleteApiAdminUsersUserIdBadgesBadgeId,postApiAuthRegister,postApiAuthLogin,getApiAuthMe,getApiBadges,getApiBadgesUserUserId,getApiBadgesProgress,putApiBadgesDisplay,getApiCommentsPostPostId,getApiCommentsCommentIdReplies,postApiComments,deleteApiCommentsId,getApiConversations,postApiConversations,getApiConversationsIdMessages,postApiConversationsIdMessages,putApiConversationsIdRead,getApiConversationsUnreadCount,getApiMetrics,getApiMetricsServer,getApiNotifications,putApiNotificationsIdRead,putApiNotificationsReadAll,getApiNotificationsUnreadCount,getApiPostsFeed,getApiPostsUserUserId,getApiPostsId,putApiPostsId,deleteApiPostsId,postApiPosts,postApiPostsIdLike,getApiPostsHashtagTag,getApiPostsTrendingHashtags,getApiPostsSearch,postApiReports,postApiUploadImage,getApiUsersUsername,putApiUsersMe,postApiUsersIdFollow,getApiUsersIdFollowers,getApiUsersIdFollowing,getApiUsersSearch,getApiUsersSuggestions,putApiUsersMePassword}};
export type GetApiAdminStatsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiAdminStats']>>>
export type GetApiAdminGrowthChartResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiAdminGrowthChart']>>>
export type GetApiAdminUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiAdminUsers']>>>
export type PutApiAdminUsersIdBanResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiAdminUsersIdBan']>>>
export type PutApiAdminUsersIdRoleResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiAdminUsersIdRole']>>>
export type PutApiAdminUsersIdResetPasswordResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiAdminUsersIdResetPassword']>>>
export type DeleteApiAdminUsersIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['deleteApiAdminUsersId']>>>
export type GetApiAdminPostsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiAdminPosts']>>>
export type DeleteApiAdminPostsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['deleteApiAdminPostsId']>>>
export type GetApiAdminCommentsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiAdminComments']>>>
export type DeleteApiAdminCommentsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['deleteApiAdminCommentsId']>>>
export type GetApiAdminReportsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiAdminReports']>>>
export type PutApiAdminReportsIdResolveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiAdminReportsIdResolve']>>>
export type DeleteApiAdminReportsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['deleteApiAdminReportsId']>>>
export type GetApiAdminBadgesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiAdminBadges']>>>
export type PostApiAdminBadgesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiAdminBadges']>>>
export type PutApiAdminBadgesIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiAdminBadgesId']>>>
export type DeleteApiAdminBadgesIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['deleteApiAdminBadgesId']>>>
export type PostApiAdminUsersUserIdBadgesBadgeIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiAdminUsersUserIdBadgesBadgeId']>>>
export type DeleteApiAdminUsersUserIdBadgesBadgeIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['deleteApiAdminUsersUserIdBadgesBadgeId']>>>
export type PostApiAuthRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiAuthRegister']>>>
export type PostApiAuthLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiAuthLogin']>>>
export type GetApiAuthMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiAuthMe']>>>
export type GetApiBadgesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiBadges']>>>
export type GetApiBadgesUserUserIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiBadgesUserUserId']>>>
export type GetApiBadgesProgressResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiBadgesProgress']>>>
export type PutApiBadgesDisplayResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiBadgesDisplay']>>>
export type GetApiCommentsPostPostIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiCommentsPostPostId']>>>
export type GetApiCommentsCommentIdRepliesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiCommentsCommentIdReplies']>>>
export type PostApiCommentsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiComments']>>>
export type DeleteApiCommentsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['deleteApiCommentsId']>>>
export type GetApiConversationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiConversations']>>>
export type PostApiConversationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiConversations']>>>
export type GetApiConversationsIdMessagesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiConversationsIdMessages']>>>
export type PostApiConversationsIdMessagesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiConversationsIdMessages']>>>
export type PutApiConversationsIdReadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiConversationsIdRead']>>>
export type GetApiConversationsUnreadCountResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiConversationsUnreadCount']>>>
export type GetApiMetricsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiMetrics']>>>
export type GetApiMetricsServerResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiMetricsServer']>>>
export type GetApiNotificationsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiNotifications']>>>
export type PutApiNotificationsIdReadResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiNotificationsIdRead']>>>
export type PutApiNotificationsReadAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiNotificationsReadAll']>>>
export type GetApiNotificationsUnreadCountResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiNotificationsUnreadCount']>>>
export type GetApiPostsFeedResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiPostsFeed']>>>
export type GetApiPostsUserUserIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiPostsUserUserId']>>>
export type GetApiPostsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiPostsId']>>>
export type PutApiPostsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiPostsId']>>>
export type DeleteApiPostsIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['deleteApiPostsId']>>>
export type PostApiPostsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiPosts']>>>
export type PostApiPostsIdLikeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiPostsIdLike']>>>
export type GetApiPostsHashtagTagResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiPostsHashtagTag']>>>
export type GetApiPostsTrendingHashtagsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiPostsTrendingHashtags']>>>
export type GetApiPostsSearchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiPostsSearch']>>>
export type PostApiReportsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiReports']>>>
export type PostApiUploadImageResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiUploadImage']>>>
export type GetApiUsersUsernameResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiUsersUsername']>>>
export type PutApiUsersMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiUsersMe']>>>
export type PostApiUsersIdFollowResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['postApiUsersIdFollow']>>>
export type GetApiUsersIdFollowersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiUsersIdFollowers']>>>
export type GetApiUsersIdFollowingResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiUsersIdFollowing']>>>
export type GetApiUsersSearchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiUsersSearch']>>>
export type GetApiUsersSuggestionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['getApiUsersSuggestions']>>>
export type PutApiUsersMePasswordResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSocialNetworkApiV1>['putApiUsersMePassword']>>>
